#!/bin/bash
RED='\033[0;31m'         #  ${RED}
GREEN='\033[0;32m'      #  ${GREEN}
NORMAL='\033[0m'
configFolder=~/configs
iFaces=ifaces.lst
cd /etc/sysconfig/network-scripts
rm -f ifcfg-eth*
service network status | grep -A1 "active devices" | grep -v "devices" | sed "s/ /\n/g" >$configFolder/$iFaces
echo -n "Reconfiguring network adapters"
mainIface=`cat $configFolder/$iFaces | grep eth`
echo "BOOTPROTO=dhcp
NM_CONTROLLED=yes
TYPE=Ethernet
DEVICE=$mainIface
ONBOOT=yes
BRIDGE=br0">ifcfg-$mainIface
echo -e "[${GREEN}DONE${NORMAL}]"
cd ~
echo -n "Restarting network service: "
service network restart >>/dev/null
echo -e "[${GREEN}DONE${NORMAL}]"

sleep 1
iFace="NULL"
ip="0.0.0.0"
for iFace in `cat $configFolder/$iFaces`;
do
        ifconfig $iFace up
        echo -en "Checking interface: $iFace: "
        if(( `ping -I $iFace -c 3 8.8.8.8 | grep -c "64 bytes from 8.8.8.8"` == 3 ));
        then
                echo -e "[${GREEN}SUCCESS${NORMAL}]"
                echo "Interface with existing internet connection: $iFace";
                break;
        fi
        echo -e "[${RED}FAILED${NORMAL}]"
done
if(( $iFace = "NULL" ))
then

                echo $iFace
                echo "no Interfaces with internet connection"
                exit -1
else
        if(( `ifconfig $iFace | grep "inet addr" | sed "s/.*inet addr://" | sed "s/  Bcast.*//" | wc -l` !=0 ));
        then
                ip=`ifconfig $iFace | grep "inet addr" | sed "s/.*inet addr://" | sed "s/  Bcast.*//"`;
        else
                echo "No ip found on interface $iFace; exiting. Try to find it manually"
                exit -2;
        fi
fi
echo "Ip found. Using $ip on interface $iFace"
echo -n "Trying to apply $ip as walrus address: "
euca_conf --register-walrus $ip>>/dev/null
if(( $? == 0 ));
then
        echo -e "[${GREEN}DONE${NORMAL}]"
        service eucalyptus-cloud restart>>/dev/null
		sleep 1800;
		echo -e "${GREEN}Walrus storage has successfully initiated${NORMAL}"
		
else
        echo -e "[${RED}FAILED${NORMAL}]"
        echo "${RED}Error has been occurred. Please check your Eucalyptus installation${NORMAL}"
fi