#!/bin/sh
sleep 200
logdir=~/logs/
distantFolder=s3://logs
date=$1
logname=eucalyptus_$date.tar.gz

#trying to connect
echo "Getting s3cmd bucket list"
s3cmd ls
if (( $? != 0 ));
then
	echo "No active storage is present"
	exit -1;
fi

#check if bucket is already exists
if (( `s3cmd ls|grep $distantFolder | wc -l` == 0 ));
then
	echo "$distantFolder not present creating"
	s3cmd mb $distantFolder
	pkill -9 s3cmd 
fi

#uploading Data to the bucket
echo "Uploading logs"
s3cmd put $logdir/$logname $distantFolder
